apiVersion: batch/v1
kind: Job
metadata:
  generateName: yb-cluster-config-
  namespace: gitops-yb
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      serviceAccount: gitops-bot
      containers:
      - name: config-job
        image: portainer/kubectl-shell
        command:
          - '/bin/sh'
          - '-c'
          - |        
              APISERVER=https://kubernetes.default.svc
              SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
              NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
              TOKEN=$(cat ${SERVICEACCOUNT}/token)
              CACERT=${SERVICEACCOUNT}/ca.crt
              kubectl config set-cluster yb --server=$APISERVER --certificate-authority=$CACERT
              kubectl config set-context yb --cluster=yb --user=default
              kubectl config set-credentials default --token=$TOKEN --user=default
              kubectl config use-context yb
              RF=3
              wt=5
              while true
              do
                if [ $(nc -z -w 1 yb-master-0.yb-masters.gitops-yb-az1 7100; echo $?) -eq 0 -a \
                     $(nc -z -w 1 yb-master-0.yb-masters.gitops-yb-az2 7100; echo $?) -eq 0 -a  \
                     $(nc -z -w 1 yb-master-0.yb-masters.gitops-yb-az3 7100; echo $?) -eq 0 ]; then
                  echo "instance is up; applying the config change"
                  kubectl exec -n gitops-yb-az1 yb-master-0 -c yb-master -- bash -c "/home/yugabyte/master/bin/yb-admin --master_addresses yb-master-0.yb-masters.gitops-yb-az1:7100,yb-master-0.yb-masters.gitops-yb-az2:7100,yb-master-0.yb-masters.gitops-yb-az3:7100 modify_placement_info ybcloud.pandora.az1,ybcloud.pandora.az2,ybcloud.pandora.az3 $RF"
                  break
                fi
                echo "instance is not ready yet; ${wt}s sleep before retry"
                sleep $wt
              done
      restartPolicy: OnFailure
  backoffLimit: 3
  # 10m deadline to wait for the image download 
  activeDeadlineSeconds: 600